### ISSUE TITLE
not present in NPM

### ISSUE THREAD

**Issue by angad-rajput-qp** [mswjs/socket.io-binding#7]
The mentioned package is not present in NPM 

"npm i @mswjs/socket.io-binding"

results in 

```
'@mswjs/socket.io-binding@*' is not in this registry.
```

**Comment by petrloukota** [comment]
I have the same issue. Looks like package socket.io-binding has not been published yet?

**Comment by amartinell** [comment]
Same issue here.

**Comment by LegendWojciechPolowniak** [comment]
@kettanaito could it be published please?

**Comment by kettanaito** [comment]
Hi. Yes, this package hasn't been published yet. I've just finished some of the updates here, now will set up the release automation and have it available on npm.
